### PR TITLE
Fix/responsiveness daily forecast cards

### PR DESCRIPTION
**Pull request by ciradu2204**
- Worked on the daily forecast responsiveness 
- Changed the components and hooks name

### CODE REVIEW

**Comment by ciradu2204** [comment]
The map is displaying well on my side. So try to refresh again @miador  and @grace-omotoso

**Review by grace-omotoso — APPROVED** [review]

**Comment by miador** [comment]
It's still same on me
image

Can someone else check too? Is it just on my side? @grace-omotoso @kpham841 @trinhcaokhoa

**Comment by kph4m** [comment]
Yeah I'm not seeing any responsive behavior for the weather cards

**Comment by ciradu2204** [comment]
Screen Shot 2022-11-23 at 13 00 15
@miador, this is how it looks on my side.

**Comment by ciradu2204** [comment]
Screen Shot 2022-11-23 at 13 01 51
 
Screen Shot 2022-11-23 at 13 07 16


@kpham841 , this is how it looks on the mobile screens and tablet. May try to refresh

**Comment by miador** [comment]
> Screen Shot 2022-11-23 at 13 00 15
> @miador, this is how it looks on my side. 

In desktop, can you try to give access to location and see if it works too?

**Pull request merged**
