### PR TITLE
Added images for background

### PR DESCRIPTION
**Pull request by namitaarya**

### CODE REVIEW

**Comment by indevi** [comment]
Hey , Please try and explore about .svg files , from [here](https://www.freepik.com/free-photos-vectors/weather-background)

**Comment by namitaarya** [comment]
Hey @ShivamTyagi12345 The linked website downloads the images in jgep format only. Is there something else u were trying to convey?

**Comment by grace-omotoso** [comment]
Still waiting for PR #21 to get merged before merging this

**Comment by indevi** [comment]
> Hey @ShivamTyagi12345 The linked website downloads the images in jgep format only. Is there something else u were trying to convey?

I tried to find a better alternative. but seems like we will have to work with  the larger files for now

**Comment by namitaarya** [comment]
Yup, i checked through. The only option is to compress these in case the size in a problem.

**Comment by miador** [comment]
Since we have decided to go with moving images, this PR is not relevant anymore.

**Pull request closed without merging**
