### PR TITLE
Resolves #18 Added food suggestion box

### LINKED ISSUE #18: Suggested food
List food the user could eat based on the weather at the bottom of the page.

image

### PR DESCRIPTION
**Pull request by ahmedemad242**
Resolves #18

### CODE REVIEW

**Comment by miador** [comment]
@trinhcaokhoa and @ShivamTyagi12345 please review the code. @norachams and @Bhawna1203 please check functionality

**Comment by indevi** [comment]
Started with the review:)

**Review by 0904-mansi — COMMENTED** [review]
It looks good to me. Clean code checked👍🏻.

**Comment by norachams** [comment]
looks really good!! I feel like more food choices should be added chocolate and coffee are repeated in a lot of different weathers.

**Comment by trinhcaokhoa** [comment]
LGTM

**Comment by pixawna** [comment]
Looking good to me:)

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
