### PR TITLE
Saved Locations Features

### PR DESCRIPTION
**Pull request by trinhcaokhoa**

### CODE REVIEW

**Comment by trinhcaokhoa** [comment]
@norachams  Please test it. @miador Please review it. Thank you

**Comment by miador** [comment]
Hey @trinhcaokhoa,
The functionality looks fine, all good. Few suggestions. Would it be better to put bookmark button to near search bar instead of bottom of it? @kpham841 what do you think?
image

**Comment by kph4m** [comment]
Yea I think it looks better on the side, heres the Figma for reference
image

**Comment by grace-omotoso** [comment]
@trinhcaokhoa please, fix merge conflicts

**Comment by norachams** [comment]
The save button looks a bit awkward as mentioned above. Other than that looks good and works really well.

**Comment by miador** [comment]
Please fix the merge conflicts and add styling @trinhcaokhoa

**Pull request closed without merging**
