### PR TITLE
Change the colour scheme based on temperature / weather type #2

### PR DESCRIPTION
**Pull request by IvyJeptoo**
the PR solves issue #2 
The background changes depending on the weather type

### CODE REVIEW

**Comment by IvyJeptoo** [comment]
@grace-omotoso @miador Kindly confirm if the backgrounds are Okay or they need changing

**Comment by miador** [comment]
Hey @IvyJeptoo,
Is there any way to cover the whole background?

**Comment by miador** [comment]
It's like this
image

**Comment by grace-omotoso** [comment]
@miador @IvyJeptoo I am also in between two opinions as to whether to have the background on the whole page or just the session with the weather card. @kpham841 design-wise, which do you think is better?

**Comment by IvyJeptoo** [comment]
> Hey @IvyJeptoo, Is there any way to cover the whole background?

I can make it cover the whole background but I thought that way it looks it a bit unique with the blending in

**Comment by IvyJeptoo** [comment]
> It's like this image



> It's like this image

I have reduced the image view height

**Pull request merged**
