### PR TITLE
Feature/hourly forecast

### LINKED ISSUE #1: Hourly Forecasts
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

### LINKED ISSUE #19: Daily weather cards
Weather cards over a 5 day period. Information includes
- Date
- Temp
- Icon based on temp
- Description
- Humidity
- Wind speed

image

### PR DESCRIPTION
**Pull request by ciradu2204**
fixes #1 
fixes #19

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@ciradu2204 please, fix merge conflicts

**Comment by trinhcaokhoa** [comment]
The code was checked. It looks nice to me.

**Comment by ciradu2204** [comment]
> @ciradu2204 please, fix merge conflicts

@grace-omotoso, I created a usefetch hook to fetch data from the API. This will avoid writing the same code every time when we want to fetch data from any API. Hence the reason for the conflict. If it's okay, I can accept my changes.

**Review by grace-omotoso — APPROVED** [review]

**Comment by miador** [comment]
I think with this PR, @0904-mansi's changes are deleted. Is it by accident or this is supposed to happen? Can you guys check?

**Comment by ciradu2204** [comment]
@miador, you are right. I mistakenly removed her code while solving the merge conflict in app.js.

**Comment by ciradu2204** [comment]
is it possible to revert back @miador? or @0904-mansi will have to create a new PR?

**Comment by miador** [comment]
Unfortunately. Because i see variable names are changed. New PR needed.

**Comment by ciradu2204** [comment]
yeah, i changed the variable names because of the useFetch hook i added!

**Pull request merged**
