### PR TITLE
Added voice assistant at the bottom right

### LINKED ISSUE #26: Add voice assistant

### PR DESCRIPTION
**Pull request by kph4m**
Resolves #26

image

Two modes:
- Search _city_: Will search up the city as if you searched the city through the search bar
- Weather for _city_: Will tell you what the weather is like and the temperature of the city

### CODE REVIEW

**Comment by miador** [comment]
I can't really see the voice assistant in deploy preview.
image

**Comment by kph4m** [comment]
Api key needs to be added to netlify

**Comment by grace-omotoso** [comment]
@kpham841 please fix conflicts

**Comment by miador** [comment]
> Api key needs to be added to netlify

Okay. After @grace-omotoso adds the api key to Netlify, we can test and merge if everything's alright.

**Comment by grace-omotoso** [comment]
> https://deploy-preview-95--mlh-prep-22-nov-prep-2-project.netlify.app/

I have added the key @miador can you check the backend to see what key you are seeing?

**Comment by miador** [comment]
Yes, it's working. It's  not showing here because it's cached. You can check from #97

**Comment by miador** [comment]
i think we can merge this

**Comment by miador** [comment]
LGTM

**Comment by miador** [comment]
I guess the assistant isn't available for mobile? @kpham841

**Pull request merged**
