### PR TITLE
Improve mobile usability #7

### PR DESCRIPTION
**Pull request by youngjun827**
Fix CSS

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@youngjun827 please, fix merge conflicts

**Review by 0904-mansi — CHANGES_REQUESTED** [review]
The text in the result box is not in a proper manner. add spacing between weather and feels. 

image

**Review by grace-omotoso — COMMENTED** [review]
Not sure this PR addresses the issue. Can we have either of @norachams or @Bhawna1203 test this change?

**Comment by indevi** [comment]
Hey @youngjun827, In case someone comes to work on this issue by OPTION NUMBER :2 ([reference](https://github.com/MLH-Fellowship/prep-project-22.NOV.PREP.2/issues/15#issuecomment-1319346817))  I will have to request you to create PRs from a new branch rather than `main` branch. To do that you can use the command `git checkout -b <Your branch name>` from the branch you want to create a clone from, You can read about the same from google :+1: Lemme know if ypu need help

Kindly close this PR.
Once you create a new Branch,by running the command mentioned above,  You can make a new PR .

**What it Accomplishes:**
---

You can continue working on different issues without having to worry about the person who will be working on 
- https://github.com/MLH-Fellowship/prep-project-22.NOV.PREP.2/issues/15

**Pull request closed without merging**
