### PR TITLE
Find current user location

### PR DESCRIPTION
**Pull request by armanmoztar**

### CODE REVIEW

**Comment by indevi** [comment]
Hey @armanmoztar  I infer that your PR solves [#3](https://github.com/MLH-Fellowship/prep-project-22.NOV.PREP.2/issues/3)

If thats right I can close the Issue

**Comment by armanmoztar** [comment]
@ShivamTyagi12345 Sorry, I didn't know that there was already a issue about this. I see that you mentioned that you'd work on it so that's my bad

**Comment by indevi** [comment]
> @ShivamTyagi12345 Sorry, I didn't know that there was already a issue about this. I see that you mentioned that you'd work on it so that's my bad

Thats Fine :)

**Comment by miador** [comment]
Can you maybe set the city in the search bar as well?
image

**Pull request closed without merging**
