### PR TITLE
Fix/refactoring

### LINKED ISSUE #94: Code refactoring/cleaning
Refactor and clean the codebase (especially App.js)

### PR DESCRIPTION
**Pull request by ciradu2204**
- This PR also fixes a bug on the map. Currently, when you click a location on the map, it does not update the location 
- It ensures the use of the useFetch to remove repeated code.
- Removed unnecessary variables

fixes #94

### CODE REVIEW

**Comment by ciradu2204** [comment]
@kpham841 , @miador , @grace-omotoso. Could you please check this PR

**Comment by miador** [comment]
@ciradu2204 this breaks the functionality of background change according to weather condition.
image

**Comment by miador** [comment]
Also while you're refactoring, can you also delete the `package-lock.json` file as well? It is for npm package manager and but are using yarn, it's not a good practice to have them both. And test if anything breaks, please

**Comment by miador** [comment]
We might not merge this before the demo just in case maybe. We can merge it after it and finally we'd have clean working cool project :)

**Comment by ciradu2204** [comment]
okay, let me check that. Thanks

**Comment by ciradu2204** [comment]
@miador, it will be good if it's merged before. At the moment, there is a bug. When you click on the map, the location does not change.

**Comment by miador** [comment]
@ciradu2204 you are right. But maybe one more person can test. @kpham841 ?

**Review by miador — APPROVED** [review]

**Comment by miador** [comment]
And also voice assistant functionality is not working in this PR. If you say "search for CITY_NAME" it will search the city. (In main project url) But here it seems broken

**Comment by miador** [comment]
Maybe latest version of main branch into your own?

**Comment by ciradu2204** [comment]
I noticed that. When I talked to @kpham841, he said there is a bug in the voice assistant functionality. It only works with known cities like Miami. Try Miami. Also, I didn't change anything on the voice assistant. 

May be @kpham841 can confirm.

**Comment by miador** [comment]
Alright then, lgtm

**Review by miador — APPROVED** [review]

**Pull request merged**
