### PR TITLE
Saved Locations

### PR DESCRIPTION
**Pull request by trinhcaokhoa**

### CODE REVIEW

**Comment by trinhcaokhoa** [comment]
@miador Please review it. @kpham841 can you double check my design. @grace-omotoso Can you review it?

**Comment by grace-omotoso** [comment]
@trinhcaokhoa I have a quick suggestion, If there is not bookmarked location and user clicks saved locations, can we have an alert that says there are not bookmarked locations? Instead of displaying a blank page4

**Comment by kph4m** [comment]
@trinhcaokhoa Looks good! And I think either way works (having a blank Saved Locations and having an alert)

**Comment by miador** [comment]
LGTM

**Comment by grace-omotoso** [comment]
@miador please, fix merge conflicts

**Comment by grace-omotoso** [comment]
Looks good now. @trinhcaokhoa please, fix conflicts

**Comment by miador** [comment]
I think this needs a rebase. I tried to do it but somehow Netlify couldn't deploy, it was working on my machine. @trinhcaokhoa can you try to fix in your local?

**Comment by trinhcaokhoa** [comment]
> I think this needs a rebase. I tried to do it but somehow Netlify couldn't deploy, it was working on my machine. @trinhcaokhoa can you try to fix in your local?

working on it

**Comment by miador** [comment]
Please pull the latest changes from main branch to be sure there won't be any conflicts

**Comment by miador** [comment]
@grace-omotoso i think we need to merge this first once the conflicts are resolved because it has many changes

**Pull request closed without merging**
