### PR TITLE
Change the colour scheme based on temperature / weather type

### PR DESCRIPTION
**Pull request by IvyJeptoo**
The PR is a solution to #2 
- I have added background images for rainy, clear, cloudy, haze and snow weather condition.
- The images may not be of good quality so it can be place holders for now.

Preview example
Screenshot from 2022-11-16 21-12-17

### CODE REVIEW

**Comment by grace-omotoso** [comment]
This is a great feature for the app. However, I noticed, the background does not change with changing weather.

**Comment by IvyJeptoo** [comment]
> This is a great feature for the app. However, I noticed, the background does not change with changing weather.

I actually changes depending with the weather location at the moment(rainy, cloudy, snowy,haze,clear). Or maybe I am the one who doesn't get it.

**Comment by trinhcaokhoa** [comment]
Checked. They're all good to me.

**Comment by miador** [comment]
Please fix the merge conflicts @IvyJeptoo

**Comment by miador** [comment]
This needs to be merged before #28

**Comment by grace-omotoso** [comment]
@IvyJeptoo could you grant me access on your forked repo so I can fix the conflict.

**Comment by IvyJeptoo** [comment]
@grace-omotoso ,I haven't been able to solve the conflicts

**Pull request closed without merging**
