### PR TITLE
Main Weather card

### LINKED ISSUE #15: Main weather card
The main weather card that users will view. Information includes
- City
- Time
- Temp
- Icon for temp
- Description
- Feels like
- Humidity
- Wind Speed
- Temp min
- Temp max

image

### PR DESCRIPTION
**Pull request by ciradu2204**
- Added the main weather card
- Worked on the responsiveness of the daily weather card and hourly forecast

fixes #15

### CODE REVIEW

**Comment by ciradu2204** [comment]
@youngjun827 , you can raise your mobile responsiveness PR in this branch.

**Comment by grace-omotoso** [comment]
@ciradu2204 please, fix merge conflicts

**Review by miador — APPROVED** [review]

**Comment by miador** [comment]
Please fix the alignment

**Comment by ciradu2204** [comment]
@miador and @grace-omotoso, I have fixed the alignment.

**Pull request merged**
